// GENERATED BY cdk_ops.sh feature:app-layer
import * as cdk from 'aws-cdk-lib';
import { Construct } from 'constructs';
import { AppLayerStageProps } from '../interfaces/app-layer';
import { AppLayerStack } from '../stacks/app-layer-stack';

/**
 * AppLayerStage
 *
 * Purpose:
 *   Environment-specific entry point that instantiates stacks with the
 *   appropriate configuration.
 */
export class AppLayerStage extends cdk.Stage {

    /**
   * AppLayerStage constructor instantiates the AppLayerStack.
   * @param scope - The construct scope
   * @param id - The stage ID
   * @param props - The stage properties
   */
  constructor(scope: Construct, id: string, props: AppLayerStageProps) {
    super(scope, id, props);

    new AppLayerStack(this, 'AppLayerStack', {
      ...props,
    });
  }
}