// GENERATED BY cdk_ops.sh feature:app-layer
import * as cdk from 'aws-cdk-lib';
import { Construct } from 'constructs';
import { AppStageProps } from '../interfaces/app-layer';
import { AppStack } from '../stacks/app';

/**
 * AppStage
 *
 * Purpose:
 *   Environment-specific entry point that instantiates stacks with the
 *   appropriate configuration.
 */
export class AppStage extends cdk.Stage {

    /**
   * AppStage constructor instantiates the AppStack.
   * @param scope - The construct scope
   * @param id - The stage ID
   * @param props - The stage properties
   */
  constructor(scope: Construct, id: string, props: AppStageProps) {
    super(scope, id, props);

    new AppStack(this, 'AppStack', {
      ...props,
    });
  }
}