// GENERATED BY cdk_ops.sh feature:base-infrastructure
import * as cdk from 'aws-cdk-lib';
import { Construct } from 'constructs';
import { BaseInfrastructureStageProps } from '../interfaces/base-infrastructure';
import { BaseInfrastructureStack } from '../stacks/base-infrastructure-stack';

/**
 * BaseInfrastructureStage
 *
 * Purpose:
 *   Environment-specific entry point that instantiates stacks with the
 *   appropriate configuration.
 */
export class BaseInfrastructureStage extends cdk.Stage {

    /**
   * BaseInfrastructureStage constructor instantiates the BaseInfrastructureStack.
   * @param scope - The construct scope
   * @param id - The stage ID
   * @param props - The stage properties
   */
  constructor(scope: Construct, id: string, props: BaseInfrastructureStageProps) {
    super(scope, id, props);

    new BaseInfrastructureStack(this, 'BaseInfrastructureStack', {
      ...props,
    });
  }
}