// GENERATED BY cdk_ops.sh feature:shared-services
import * as cdk from 'aws-cdk-lib';
import { Construct } from 'constructs';
import { FoundationStageProps } from '../interfaces/shared-services';
import { SharedServicesStack } from '../stacks/shared-services';
import { BaseInfrastructureStack } from '../stacks/base-infrastructure';

/**
 * FoundationsStage
 *
 * Purpose:
 *   Environment-specific entry point that instantiates stacks with the
 *   appropriate configuration.
 */
export class FoundationsStage extends cdk.Stage {
  /**
   * FoundationsStage constructor instantiates the SharedServicesStack & the InfrastructureStack.
   * @param scope - The construct scope
   * @param id - The stage ID
   * @param props - The stage properties
   */
  constructor(scope: Construct, id: string, props: FoundationStageProps) {
    super(scope, id, props);

    const sharedServicesStack = new SharedServicesStack(
      this,
      'SharedServicesStack',
      {
        description:
          'Shared services stack for foundational resources (e.g., Cognito, ECR)',
        tags: {
          ManagedByPipeline: 'App-CdkPipeline',
        },
        ...props,
      },
    );

    const infrastructureStack = new BaseInfrastructureStack(
      this,
      'InfrastructureStack',
      {
        description:
          'Infrastructure stack for foundational resources (e.g., VPC, RDS, S3)',
        tags: {
          ManagedByPipeline: 'App-CdkPipeline',
        },
        ...props,
      },
    );

    infrastructureStack.addDependency(sharedServicesStack);
  }
}
