// GENERATED BY cdk_ops.sh feature:shared-services
import * as cdk from 'aws-cdk-lib';
import { Construct } from 'constructs';
import { FoundationStageProps } from '../interfaces/pipeline';
import { SharedServicesStack } from '../stacks/shared-services';
import { BaseInfrastructureStack } from '../stacks/base-infrastructure';

/**
 * FoundationsStage
 *
 * Purpose:
 *   Environment-specific entry point that instantiates stacks with the
 *   appropriate configuration.
 */
export class FoundationsStage extends cdk.Stage {
  /**
   * FoundationsStage constructor instantiates the SharedServicesStack & the InfrastructureStack.
   * @param scope - The construct scope
   * @param id - The stage ID
   * @param props - The stage properties
   */
  constructor(scope: Construct, id: string, props: FoundationStageProps) {
    super(scope, id, props);

    const sharedServicesStack = new SharedServicesStack(
      this,
      'SharedServicesStack',
      {
        stage: props.stage,
        env: props.env,
      },
    );

    // const infrastructureStack = new BaseInfrastructureStack(
    //   this,
    //   'InfrastructureStack',
    //   {
    //     stage: props.stage,
    //     env: props.env,
    //   },
    // );

    // infrastructureStack.addDependency(
    //   sharedServicesStack,
    //   'Ensure SharedServicesStack is deployed before BaseInfrastructureStack.',
    // );
  }
}
