// GENERATED BY cdk_ops.sh feature:shared-services
import * as cdk from 'aws-cdk-lib';
import { Construct } from 'constructs';
import { SharedServicesStageProps } from '../interfaces/shared-services';
import { SharedServicesStack } from '../stacks/shared-services-stack';

/**
 * SharedServicesStage
 *
 * Purpose:
 *   Environment-specific entry point that instantiates stacks with the
 *   appropriate configuration.
 */
export class SharedServicesStage extends cdk.Stage {

  /**
   * SharedServicesStage constructor instantiates the SharedServicesStack.
   * @param scope - The construct scope
   * @param id - The stage ID
   * @param props - The stage properties
   */
  constructor(scope: Construct, id: string, props: SharedServicesStageProps) {
    super(scope, id, props);

    new SharedServicesStack(this, 'SharedServicesStack', {
      ...props,
    });
  }
}
