// GENERATED BY cdk_ops.sh feature:shared-services1
import * as cdk from 'aws-cdk-lib';
import { Construct } from 'constructs';
import { SharedServices1StageProps } from '../interfaces/shared-services';
import { SharedServices1Stack } from '../stacks/shared-services1-stack';

/**
 * SharedServices1Stage
 *
 * Purpose:
 *   Environment-specific entry point that instantiates stacks with the
 *   appropriate configuration.
 */
export class SharedServices1Stage extends cdk.Stage {
  constructor(scope: Construct, id: string, props: SharedServices1StageProps) {
    super(scope, id, props);

    new SharedServices1Stack(this, 'SharedServices1Stack', {
      ...props,
    });
  }
}
