// GENERATED BY cdk_ops.sh feature:app-layer
import * as cdk from 'aws-cdk-lib';
import { Stage } from '../config/environment';

/**
 * AppProps
 *
 * Purpose:
 *   High-level, user-facing properties for configuring the App feature.
 *   Keep this small and stable; apply defaults in builders.
 */
export interface AppProps {}

/**
 * AppConstructProps
 *
 * Purpose:
 *   Properties required by AppConstruct. Typically a normalized subset
 *   of AppProps.
 */
export interface AppConstructProps {}

/**
 * AppBuilderProps
 *
 * Purpose:
 *   Constructor props for AppBuilder.
 *   Often you can alias this to AppProps.
 */
export interface AppBuilderProps extends AppProps {}

/**
 * AppStackProps
 *
 * Purpose:
 *   Strongly-typed Stack props for AppStack.
 */
export interface AppStackProps extends cdk.StackProps, AppProps {
    stage:Stage;
    vpc: cdk.aws_ec2.IVpc;
}

/**
 * AppStageProps
 *
 * Purpose:
 *   Strongly-typed Stage props for AppStage.
 */
export interface AppStageProps extends cdk.StageProps, AppProps {
  stage: Stage;
  vpc: cdk.aws_ec2.IVpc;
}