// GENERATED BY cdk_ops.sh feature:app-layer
import * as cdk from 'aws-cdk-lib';

/**
 * AppLayerProps
 *
 * Purpose:
 *   High-level, user-facing properties for configuring the AppLayer feature.
 *   Keep this small and stable; apply defaults in builders.
 */
export interface AppLayerProps {}

/**
 * AppLayerConstructProps
 *
 * Purpose:
 *   Properties required by AppLayerConstruct. Typically a normalized subset
 *   of AppLayerProps.
 */
export interface AppLayerConstructProps {}

/**
 * AppLayerBuilderProps
 *
 * Purpose:
 *   Constructor props for AppLayerBuilder.
 *   Often you can alias this to AppLayerProps.
 */
export interface AppLayerBuilderProps extends AppLayerProps {}

/**
 * AppLayerStackProps
 *
 * Purpose:
 *   Strongly-typed Stack props for AppLayerStack.
 */
export interface AppLayerStackProps extends cdk.StackProps, AppLayerProps {}

/**
 * AppLayerStageProps
 *
 * Purpose:
 *   Strongly-typed Stage props for AppLayerStage.
 */
export interface AppLayerStageProps extends cdk.StageProps, AppLayerProps {}