// GENERATED BY cdk_ops.sh feature:base-infrastructure
import * as cdk from 'aws-cdk-lib';
import { InterfaceVpcEndpointAwsService } from 'aws-cdk-lib/aws-ec2';
import { LogGroup } from 'aws-cdk-lib/aws-logs';
import { Stage } from '../config/environment';
import { AuroraDbConfig, RdsBastionConfig } from './bastion';

/**
 * BaseInfrastructureProps
 *
 * Purpose:
 *   High-level, user-facing properties for configuring the BaseInfrastructure feature.
 *   Keep this small and stable; apply defaults in builders.
 */
export interface BaseInfrastructureProps {
  stage: Stage;
  pipelineName: string;
  network: NetworkConfig;
  exportNames?: {
    vpcId?: string;
    appClientSgId?: string;
  };
}

/**
 * BaseInfrastructureStackProps
 *
 * Purpose:
 *   Strongly-typed Stack props for BaseInfrastructureStack.
 */
export interface BaseInfrastructureStackProps extends cdk.StackProps {
  stage: Stage;
  config: IBaseInfrastructureConfig;
}

export type NetworkConfig = {
  maxAzs?: number; // default 2
  natGateways?: number; // default 1 (prod: 2)
  vpcCidr?: string; // optional CIDR
  logGrp: LogGroup;
  vpcEndpoints?: InterfaceVpcEndpointAwsService[];
  cidrMaskPublic?: number;
  cidrMaskPrivate: number;
  idPrefix: string;
};

export interface IBaseInfrastructureConfig {
  network: NetworkConfig;
  bastion: RdsBastionConfig;
  rds: AuroraDbConfig;
  pipelineName: string;
  exportNames?: {
    vpcId?: string;
    appClientSgId?: string;
  };
}