// GENERATED BY cdk_ops.sh feature:base-infrastructure
import * as cdk from 'aws-cdk-lib';
import { InterfaceVpcEndpointAwsService } from 'aws-cdk-lib/aws-ec2';
import { LogGroup } from 'aws-cdk-lib/aws-logs';

/**
 * BaseInfrastructureProps
 *
 * Purpose:
 *   High-level, user-facing properties for configuring the BaseInfrastructure feature.
 *   Keep this small and stable; apply defaults in builders.
 */
export interface BaseInfrastructureProps {
    network: NETWORK_CONFIG;
}

/**
 * BaseInfrastructureConstructProps
 *
 * Purpose:
 *   Properties required by BaseInfrastructureConstruct. Typically a normalized subset
 *   of BaseInfrastructureProps.
 */
export interface BaseInfrastructureConstructProps {}

/**
 * BaseInfrastructureBuilderProps
 *
 * Purpose:
 *   Constructor props for BaseInfrastructureBuilder.
 *   Often you can alias this to BaseInfrastructureProps.
 */
export interface BaseInfrastructureBuilderProps extends BaseInfrastructureProps {}

/**
 * BaseInfrastructureStackProps
 *
 * Purpose:
 *   Strongly-typed Stack props for BaseInfrastructureStack.
 */
export interface BaseInfrastructureStackProps extends cdk.StackProps, BaseInfrastructureProps {}

/**
 * BaseInfrastructureStageProps
 *
 * Purpose:
 *   Strongly-typed Stage props for BaseInfrastructureStage.
 */
export interface BaseInfrastructureStageProps extends cdk.StageProps, BaseInfrastructureProps {}

export type NETWORK_CONFIG = {
  maxAzs?: number; // default 2
  natGateways?: number; // default 1 (prod: 2)
  vpcCidr?: string; // optional CIDR
  logGrp: LogGroup;
  vpcEndpoints?: InterfaceVpcEndpointAwsService[];
  cidrMaskPublic?: number; 
  cidrMaskPrivate: number;
  idPrefix: string;
}   