// GENERATED BY cdk_ops.sh feature:shared-services
import * as cdk from 'aws-cdk-lib';

/**
 * SharedServicesProps
 *
 * Purpose:
 *   High-level, user-facing properties for configuring the SharedServices feature.
 *   Keep this small and stable; apply defaults in builders.
 */
export interface SharedServicesProps {}

/**
 * SharedServicesConstructProps
 *
 * Purpose:
 *   Properties required by SharedServicesConstruct. Typically a normalized subset
 *   of SharedServicesProps.
 */
export interface SharedServicesConstructProps {}

/**
 * SharedServicesBuilderProps
 *
 * Purpose:
 *   Constructor props for SharedServicesBuilder.
 *   Often you can alias this to SharedServicesProps.
 */
export interface SharedServicesBuilderProps extends SharedServicesProps {}

/**
 * SharedServicesStackProps
 *
 * Purpose:
 *   Strongly-typed Stack props for SharedServicesStack.
 */
export interface SharedServicesStackProps extends cdk.StackProps, SharedServicesProps {}

/**
 * SharedServicesStageProps
 *
 * Purpose:
 *   Strongly-typed Stage props for SharedServicesStage.
 */
export interface SharedServicesStageProps extends cdk.StageProps, SharedServicesProps {}