// GENERATED BY cdk_ops.sh feature:shared-services
import * as cdk from 'aws-cdk-lib';
import * as events from 'aws-cdk-lib/aws-events';
import { Stage } from '../config/environment';


/**
 * SharedServicesProps
 *
 * Purpose:
 *   High-level, user-facing properties for configuring the SharedServices feature.
 *   Keep this small and stable; apply defaults in builders.
 */
export interface SharedServicesProps {
  ecr?: ECR_CONFIG;
  oidc?: OIDC_CONFIG;
  migrationOps?: MIGRATION_OPS_CONFIG;
  
}

/**
 * SharedServicesConstructProps
 *
 * Purpose:
 *   Properties required by SharedServicesConstruct. Typically a normalized subset
 *   of SharedServicesProps.
 */
export interface SharedServicesConstructProps {}

/**
 * SharedServicesBuilderProps
 *
 * Purpose:
 *   Constructor props for SharedServicesBuilder.
 *   Often you can alias this to SharedServicesProps.
 */
export interface SharedServicesBuilderProps extends SharedServicesProps {
 
}

export type ECR_CONFIG = {
    REPO_NAME: string;
    ImageScanOnPush: boolean;
    ImageTagMutability: cdk.aws_ecr.TagMutability;
    Encryption: cdk.aws_ecr.RepositoryEncryption;
    LifecycleMaxImageAgeDays: number;
    RemovalPolicy: cdk.RemovalPolicy;
}
 
export type OIDC_CONFIG = {
  applicationRepository: {
    owner: string;
    name: string;
    branch: string;
  };
  provider: {
    name: string;     
    url: string;
    clientIds: string[];
    thumbprints: string[];
}
  ciRole: {
    name: string;
    description: string;
    stringEqualityConditions: Record<string, string>;
    stringLikeConditions: Record<string, string>; 
  };
}

export type MIGRATION_OPS_CONFIG = {
  automationRunbookName: string;
  runCommandDocumentName: string;
  target:{
    instance:{
      tagKey: string;
      tagValue: string;
    },
    stack:{
      name: string;
    }
  }
  
};

/**
 * SharedServicesStackProps
 *
 * Purpose:
 *   Strongly-typed Stack props for SharedServicesStack.
 */
export interface SharedServicesStackProps extends cdk.StackProps {
  pipelineName?: string;
}

/**
 * SharedServicesStageProps
 *
 * Purpose:
 *   Strongly-typed Stage props for SharedServicesStage.
 */
export interface SharedServicesStageProps extends cdk.StageProps, SharedServicesProps {
  pipelineName?: string;
}


export interface EventRoute {
  /** A name/id for the rule */
  readonly name: string;

  /** Where the events come from */
  readonly eventBus?: events.IEventBus;

  /** Match incoming events */
  readonly eventPattern: events.EventPattern;

  /** Where the matched events go */
  readonly targets: events.IRuleTarget[];

  /** Optional: format/transform the payload per-target (advanced) */
  readonly input?: events.RuleTargetInput;

  /** Optional: enable/disable */
  readonly enabled?: boolean;
}

export interface EventRouterProps {
  readonly routes: EventRoute[];
}


export interface Waney93CicdObservabilityStackProps extends cdk.StackProps {
  stage: Stage;  
  env:cdk.Environment;
}

export interface OpsRunbookConstructProps {
  migrationOps?: MIGRATION_OPS_CONFIG;
}