// GENERATED BY cdk_ops.sh feature:shared-services
import * as cdk from 'aws-cdk-lib';
import * as events from 'aws-cdk-lib/aws-events';
import { Stage } from '../config/environment';


/**
 * SharedServicesProps
 *
 * Purpose:
 *   High-level, user-facing properties for configuring the SharedServices feature.
 *   Keep this small and stable; apply defaults in builders.
 */
export interface SharedServicesProps {
  ecr?: ECR_CONFIG;
  oidc?: OIDC_CONFIG;
  migrationOps?: MIGRATION_OPS_CONFIG;
  cognito?: COGNITO_CONFIG;
  migrationStorage?: MIGRATION_STORAGE_CONFIG;
  
}

/**
 * SharedServicesBuilderProps
 *
 * Purpose:
 *   Constructor props for SharedServicesBuilder.
 *   Often you can alias this to SharedServicesProps.
 */
export interface SharedServicesBuilderProps extends SharedServicesProps {
 
}
/**
 * S3StorageConstructProps
 *
 * Purpose:
 *   Properties for configuring the S3StorageConstruct, which defines resources related to S3 storage, such as S3 buckets.
 */
export interface S3StorageConstructProps {
  name: string;
  removalPolicy: cdk.RemovalPolicy;
  autoDeleteObjects: boolean;
  bucketId: string;
  enforceSSL?: boolean;
  versioned?: boolean;
  encryption?: cdk.aws_s3.BucketEncryption;
}

/**
 * DynamoDBTableConstructProps
 *
 * Purpose:
 *   Properties for configuring a DynamoDB table construct, which defines resources related to DynamoDB tables used in migration storage.
 */
export interface DynamoDBTableConstructProps {
  name: string;
  removalPolicy: cdk.RemovalPolicy;
  tableId: string;
}

export type ECR_CONFIG = {
    REPO_NAME: string;
    ImageScanOnPush: boolean;
    ImageTagMutability: cdk.aws_ecr.TagMutability;
    Encryption: cdk.aws_ecr.RepositoryEncryption;
    LifecycleMaxImageAgeDays: number;
    RemovalPolicy: cdk.RemovalPolicy;
}
 
export type OIDC_CONFIG = {
  applicationRepository: {
    owner: string;
    name: string;
    branch: string;
  };
  provider: {
    name: string;     
    url: string;
    clientIds: string[];
    thumbprints: string[];
}
  ciRole: {
    name: string;
    description: string;
    stringEqualityConditions: Record<string, string>;
    stringLikeConditions: Record<string, string>; 
  };
}

export type MIGRATION_OPS_CONFIG = {
  automationRunbookName: string;
  runCommandDocumentName: string;
  target: {
    instance: {
      tagKey: string;
      tagValue: string;
    };
    stack: {
      name?: string;
    };
  };
  script?: {
    folderPath: string;
    entryFile: string;
    description?: string;
  };
};

export type COGNITO_CONFIG = {
  app: {
    name: string;
    callbackUrls: string[];
    logoutUrls: string[];
    secret: { name: string };
  };
  customDomainName: string;
  acmCertificateArn: string;
  userPoolSelfSignUpEnabled: boolean;
  allowUsernameSignIn: boolean;
  removalPolicy: cdk.RemovalPolicy;
};

/**
 * MIGRATION_STORAGE_CONFIG
 *
 * Purpose:
 *   Configuration for migration storage resources, such as S3 buckets or DynamoDB tables, used in migration operations.
 *   This can include bucket names, table names, and any relevant settings for those resources.
 */
export type MIGRATION_STORAGE_CONFIG = {
  s3Bucket: S3StorageConstructProps;
  dynamoDBTable: DynamoDBTableConstructProps;
};

/**
 * SharedServicesStackProps
 *
 * Purpose:
 *   Strongly-typed Stack props for SharedServicesStack.
 */
export interface SharedServicesStackProps extends cdk.StackProps {
  pipelineName?: string;
  acmCertificateArnName?: string;
}

/**
 * SharedServicesStageProps
 *
 * Purpose:
 *   Strongly-typed Stage props for FoundationsStage.
 */
export interface FoundationStageProps extends cdk.StageProps, SharedServicesProps {
  pipelineName?: string;
  acmCertificateArnName?: string;
  stage:Stage;
}


export interface EventRoute {
  /** A name/id for the rule */
  readonly name: string;

  /** Where the events come from */
  readonly eventBus?: events.IEventBus;

  /** Match incoming events */
  readonly eventPattern: events.EventPattern;

  /** Where the matched events go */
  readonly targets: events.IRuleTarget[];

  /** Optional: format/transform the payload per-target (advanced) */
  readonly input?: events.RuleTargetInput;

  /** Optional: enable/disable */
  readonly enabled?: boolean;
}

export interface EventRouterProps {
  readonly routes: EventRoute[];
}


export interface Waney93CicdObservabilityStackProps extends cdk.StackProps {
  stage: Stage;  
  env:cdk.Environment;
}

export interface OpsRunbookConstructProps {
  migrationOps?: MIGRATION_OPS_CONFIG;
}