// GENERATED BY cdk_ops.sh feature:app-layer
import * as cdk from 'aws-cdk-lib';
import { Construct } from 'constructs';
import { AppLayerStackProps } from '../interfaces/app-layer';
import { AppLayerBuilder } from '../builders/app-layer-builder';

/**
 * AppLayerStack
 *
 * Purpose:
 *   Stack entry point for the AppLayer feature area.
 *   Keep this thin; orchestration belongs in builders.
 */
export class AppLayerStack extends cdk.Stack {

    /**
    * AppLayerStack constructor that instantiates AppLayerBuilder
    * @param scope - The construct scope
    * @param id - The stack ID
    * @param props - The stack properties
    */
  constructor(scope: Construct, id: string, props: AppLayerStackProps) {
    super(scope, id, props);

    new AppLayerBuilder(this, 'AppLayerBuilder', props)
      .build()
      .outputs();

    // Optional tagging convention
    cdk.Tags.of(this).add('ManagedBy', 'waney93-aws-reference-architecture');
  }
}