// GENERATED BY cdk_ops.sh feature:app-layer
import * as cdk from 'aws-cdk-lib';
import { Construct } from 'constructs';
import { AppStackProps } from '../interfaces/app-layer';
import { AppBuilder } from '../builders/app';

/**
 * AppStack
 *
 * Purpose:
 *   Stack entry point for the App feature area.
 *   Keep this thin; orchestration belongs in builders.
 */
export class AppStack extends cdk.Stack {

    /**
    * AppStack constructor that instantiates AppBuilder
    * @param scope - The construct scope
    * @param id - The stack ID
    * @param props - The stack properties
    */
  constructor(scope: Construct, id: string, props: AppStackProps) {
    super(scope, id, props);

    new AppBuilder(this, 'AppBuilder', props)
      .build()
      .outputs();

    // Optional tagging convention
    cdk.Tags.of(this).add('ManagedBy', 'waney93-aws-reference-architecture');
  }
}