// GENERATED BY cdk_ops.sh feature:base-infrastructure
import * as cdk from 'aws-cdk-lib';
import { Construct } from 'constructs';
import { BaseInfrastructureStackProps } from '../interfaces/base-infrastructure';
import { BaseInfrastructureBuilder } from '../builders/base-infrastructure';

/**
 * BaseInfrastructureStack
 *
 * Purpose:
 *   Stack entry point for the BaseInfrastructure feature area.
 *   Keep this thin; orchestration belongs in builders.
 */
export class BaseInfrastructureStack extends cdk.Stack {

    /**
    * BaseInfrastructureStack constructor that instantiates BaseInfrastructureBuilder
    * @param scope - The construct scope
    * @param id - The stack ID
    * @param props - The stack properties
    */
  constructor(scope: Construct, id: string, props: BaseInfrastructureStackProps) {
    super(scope, id, props);

    new BaseInfrastructureBuilder(this, 'BaseInfrastructureBuilder', props)
      .build()
      .outputs();

    // Optional tagging convention
    cdk.Tags.of(this).add('ManagedBy', 'waney93-aws-reference-architecture');
  }
}