// GENERATED BY cdk_ops.sh feature:base-infrastructure
import * as cdk from 'aws-cdk-lib';
import * as iam from 'aws-cdk-lib/aws-iam';
import * as ec2 from 'aws-cdk-lib/aws-ec2';
import * as ssm from 'aws-cdk-lib/aws-ssm';
import { LogGroup, RetentionDays } from 'aws-cdk-lib/aws-logs';
import { Construct } from 'constructs';
import {
  BaseInfrastructureStackProps,
  NETWORK_CONFIG,
} from '../interfaces/base-infrastructure';
import { BaseInfrastructureBuilder } from '../builders/base-infrastructure';
import {
  MigrationOperations,
  RdsBastionConfigBuilderProps,
} from '../interfaces/bastion';
import { SharedServicesStack } from './shared-services';
import {
  getDatabaseMigrationParameterConfig,
  getScriptMigrationParameterConfig,
} from '../config/migrations/templates';
import { Stage } from '../config/environment';

/**
 * BaseInfrastructureStack
 *
 * Purpose:
 *   Stack entry point for the BaseInfrastructure feature area.
 *   Keep this thin; orchestration belongs in builders.
 */
export class BaseInfrastructureStack extends cdk.Stack {
  /**
   * BaseInfrastructureStack constructor that instantiates BaseInfrastructureBuilder
   * @param scope - The construct scope
   * @param id - The stack ID
   * @param props - The stack properties
   */
  constructor(
    scope: Construct,
    id: string,
    props: BaseInfrastructureStackProps,
  ) {
    super(scope, id, props);

    new BaseInfrastructureBuilder(this, 'BaseInfrastructureBuilder', {
      network: BaseInfrastructureStack.getNetworkConfig(this),
      stage: props.stage,
      rdsBastion: BaseInfrastructureStack.getBastionConfig(props.stage, this),
    })
      .withNetwork()
      .withRdsBastion()
      .outputs();

    // Optional tagging convention
    cdk.Tags.of(this).add('ManagedBy', 'waney93-aws-reference-architecture');
  }

  static getNetworkConfig(scope: Construct): NETWORK_CONFIG {
    return {
      maxAzs: 2,
      natGateways: 1,
      logGrp: new LogGroup(scope, 'VpcFlowLogs', {
        retention: RetentionDays.ONE_DAY,
        removalPolicy: cdk.RemovalPolicy.DESTROY, // keep RETAIN in prod
      }),
      cidrMaskPrivate: 24,
      cidrMaskPublic: 24,
      idPrefix: 'BaseVpc',
    };
  }

  static getBastionConfig(
    stage: Stage,
    scope: Construct,
  ): RdsBastionConfigBuilderProps {
    const Params = {
      config: {
        script: getScriptMigrationParameterConfig(stage),
      },
      databaseCredentials: getDatabaseMigrationParameterConfig(stage),
    };

    const loginSecretName = ssm.StringParameter.valueForStringParameter(
      scope,
      Params.databaseCredentials.loginSecretName,
    );
    const appUserName = ssm.StringParameter.valueForStringParameter(
      scope,
      Params.databaseCredentials.appUser.name,
    );
    const appUserSecret = ssm.StringParameter.valueForStringParameter(
      scope,
      Params.databaseCredentials.appUser.secretName,
    );
    if(!Params.config.script){
      throw new Error('Script migration config is required to create RdsBastion construct.');
    }
    const folderPath = ssm.StringParameter.valueForStringParameter(
      scope,
      Params.config.script.folderPath,
    );
    const entryFile = ssm.StringParameter.valueForStringParameter(
      scope,
      Params.config.script.entryFile,
    );
    const description = ssm.StringParameter.valueForStringParameter(
      scope,
      Params.config.script.description?? 'Migration script for on-prem to RDS migration',
    );
    const migrationOps: MigrationOperations = {
      config: {
        ...SharedServicesStack.getMigrationOpsConfig(),
        script: {
          folderPath,
          entryFile,
          description,
        },
      },
      databaseCredentials: {
        loginSecretName,
        appUser: {
          name: appUserName,
          secretName: appUserSecret,
        },
      },
    };

    return {
      userDataCommands: [
        'set -eux',
        'sudo dnf -y update',
        'sudo dnf -y install --allowerasing curl postgresql17 python3 jq unzip',
      ],

      subnetSelection: { subnetType: ec2.SubnetType.PRIVATE_WITH_EGRESS },
      instance: {
        type: ec2.InstanceType.of(ec2.InstanceClass.T3, ec2.InstanceSize.NANO),
        ami: ec2.MachineImage.latestAmazonLinux2023(),
      },
      securityGroupPorts: [
        {
          port: ec2.Port.tcp(5432),
          description: 'Allow outbound access to databases',
        },
      ],
      migrationOps,
    };
  }
}
