// GENERATED BY cdk_ops.sh feature:base-infrastructure
import * as cdk from 'aws-cdk-lib';
import { LogGroup, RetentionDays } from 'aws-cdk-lib/aws-logs';
import { Construct } from 'constructs';
import {
  BaseInfrastructureStackProps,
  NETWORK_CONFIG,
} from '../interfaces/base-infrastructure';
import { BaseInfrastructureBuilder } from '../builders/base-infrastructure';

/**
 * BaseInfrastructureStack
 *
 * Purpose:
 *   Stack entry point for the BaseInfrastructure feature area.
 *   Keep this thin; orchestration belongs in builders.
 */
export class BaseInfrastructureStack extends cdk.Stack {
  /**
   * BaseInfrastructureStack constructor that instantiates BaseInfrastructureBuilder
   * @param scope - The construct scope
   * @param id - The stack ID
   * @param props - The stack properties
   */
  constructor(
    scope: Construct,
    id: string,
    props: BaseInfrastructureStackProps,
  ) {
    super(scope, id, props);

    new BaseInfrastructureBuilder(this, 'BaseInfrastructureBuilder', {
      network: this.getNetworkConfig(),
    })
     // .withNetwork()
      //.outputs();

    // Optional tagging convention
    cdk.Tags.of(this).add('ManagedBy', 'waney93-aws-reference-architecture');
  }

  getNetworkConfig(): NETWORK_CONFIG {
    return {
      maxAzs: 2,
      natGateways: 1,
      logGrp: new LogGroup(this, 'VpcFlowLogs', {
        retention: RetentionDays.ONE_DAY,
        removalPolicy: cdk.RemovalPolicy.DESTROY, // keep RETAIN in prod
      }),
      cidrMaskPrivate: 24,
      cidrMaskPublic: 24,
      idPrefix: 'BaseVpc',
    };
  }
}
