// GENERATED BY cdk_ops.sh feature:shared-services
import * as cdk from 'aws-cdk-lib';
import { Construct } from 'constructs';
import { ECR_CONFIG, OIDC_CONFIG, SharedServicesStackProps } from '../interfaces/shared-services';
import { SharedServicesBuilder } from '../builders/shared-services';

/**
 * SharedServicesStack
 *
 * Purpose:
 *   Stack entry point for the SharedServices feature area.
 *   Keep this thin; orchestration belongs in builders.
 */
export class SharedServicesStack extends cdk.Stack {

  /**
   * SharedServicesStack constructor that instantiates SharedServicesBuilder
   * @param scope - The construct scope
   * @param id - The stack ID
   * @param props - The stack properties
   */
  constructor(scope: Construct, id: string, props: SharedServicesStackProps) {
    super(scope, id, props);
    const ecr_config: ECR_CONFIG = this.getEcrConfig();
    const oidc_config: OIDC_CONFIG = this.getOidcConfig();

    new SharedServicesBuilder(this, 'SharedServicesBuilder', { ...props, ecr: ecr_config, oidc: oidc_config })
      .withEcr()
      .withCiEcrPushRole()
      .withGitHubOidc()
      .build()
      .outputs();
    // Optional tagging convention
    cdk.Tags.of(this).add('ManagedBy', 'waney93-aws-reference-architecture');
  }

  getEcrConfig(): ECR_CONFIG {
    return {
      REPO_NAME: 'waney93-ecr-repo',
      ImageScanOnPush: true,
      ImageTagMutability: cdk.aws_ecr.TagMutability.IMMUTABLE,
      Encryption: cdk.aws_ecr.RepositoryEncryption.KMS,
      LifecycleMaxImageAgeDays: 2,
      RemovalPolicy: cdk.RemovalPolicy.DESTROY,
    };
  }

  getOidcConfig(): OIDC_CONFIG {
    return {
      applicationRepository: {
        owner: 'Waney93LLC',
        name: 'djangoproject',
        branch: 'main',
      },
      provider: {
        name: 'GitHub',
        url: 'https://token.actions.githubusercontent.com',
        clientIds: ['sts.amazonaws.com'],
        thumbprints: [
          '6938fd4d98bab03faadb97b34396831e3780aea1',
          '1c58a3a8518e8759bf075b76b750d4f2df264fcd',
        ],
      },
      ciRole: {
        name: 'DjangoProjectGitHubActionsRole',
        description: 'Role for GitHub Actions from djangoproject to assume via OIDC',
        stringEqualityConditions: {
          'token.actions.githubusercontent.com:aud': 'sts.amazonaws.com',
        },
        stringLikeConditions: {
          'token.actions.githubusercontent.com:sub':
            'repo:Waney93LLC/djangoproject:*',
        },
      },
    };}
}
