// GENERATED BY cdk_ops.sh feature:shared-services
import * as cdk from 'aws-cdk-lib';
import { Construct } from 'constructs';
import {
  SharedServicesStackProps,
} from '../interfaces/shared-services';
import { SharedServicesBuilder } from '../builders/shared-services';
import { getWaney93PipelineConfig } from '../config/pipelines/waney93';

/**
 * SharedServicesStack
 *
 * Purpose:
 *   Stack entry point for the SharedServices feature area.
 *   Keep this thin; orchestration belongs in builders.
 */
export class SharedServicesStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props: SharedServicesStackProps) {
    super(scope, id, props);
    const config = getWaney93PipelineConfig(this, props.stage);

    new SharedServicesBuilder(this, 'SharedServicesBuilder', {
      stage: props.stage,
      config: config.sharedServices,
    })
      // .withEcr()
      // .withCiEcrPushRole()
      // .withGitHubOidc()
      // .withMigrationBootstrap()
      // .withMigrationStorage()
      // .withCognito()
      // .outputs();
  }
}
