// GENERATED BY cdk_ops.sh feature:shared-services
import * as cdk from 'aws-cdk-lib';
import { Construct } from 'constructs';
import { SharedServicesStackProps } from '../interfaces/shared-services';
import { SharedServicesBuilder } from '../builders/shared-services-builder';

/**
 * SharedServicesStack
 *
 * Purpose:
 *   Stack entry point for the SharedServices feature area.
 *   Keep this thin; orchestration belongs in builders.
 */
export class SharedServicesStack extends cdk.Stack {

  /**
   * SharedServicesStack constructor that instantiates SharedServicesBuilder
   * @param scope - The construct scope
   * @param id - The stack ID
   * @param props - The stack properties
   */
  constructor(scope: Construct, id: string, props: SharedServicesStackProps) {
    super(scope, id, props);

    new SharedServicesBuilder(this, 'SharedServicesBuilder', props)
      .build()
      .outputs();

    // Optional tagging convention
    cdk.Tags.of(this).add('ManagedBy', 'waney93-aws-reference-architecture');
  }
}
