// GENERATED BY cdk_ops.sh feature:shared-services1
import * as cdk from 'aws-cdk-lib';
import { Construct } from 'constructs';
import { SharedServices1StackProps } from '../interfaces/shared-services';
import { SharedServices1Builder } from '../builders/shared-services-builder';

/**
 * SharedServices1Stack
 *
 * Purpose:
 *   Stack entry point for the SharedServices1 feature area.
 *   Keep this thin; orchestration belongs in builders.
 */
export class SharedServices1Stack extends cdk.Stack {
  constructor(scope: Construct, id: string, props: SharedServices1StackProps) {
    super(scope, id, props);

    new SharedServices1Builder(this, 'SharedServices1Builder', props)
      .build()
      .outputs();

    // Optional tagging convention
    cdk.Tags.of(this).add('ManagedBy', 'waney93-aws-reference-architecture');
  }
}
