// GENERATED BY cdk_ops.sh feature:app-layer
import { Construct } from 'constructs';
import { AppBuilderProps, AppConstructProps } from '../interfaces/app-layer';
import { AppConstruct } from '../constructs/app-layer';

/**
 * AppBuilder
 *
 * Purpose:
 *   Composition layer that orchestrates one or more constructs into a cohesive
 *   feature (e.g., Cognito, VPC, ECS, CI/CD).
 *
 * Notes:
 *   - Apply defaults + normalize props here.
 *   - Keep public methods fluent (return this) to support chaining.
 */
export class AppBuilder {
  private readonly scope: Construct;
  private readonly idPrefix: string;
  private readonly props: Required<AppBuilderProps>;

  /**
   * AppBuilder constructor creates a builder that orchestrates
   * one or more constructs into a cohesive feature.
   * @param scope - The construct scope
   * @param idPrefix - The ID prefix for the resources
   * @param props - The builder properties
   */
  constructor(scope: Construct, idPrefix: string, props: AppBuilderProps) {
    this.scope = scope;
    this.idPrefix = idPrefix;

    // Apply defaults + normalize here
    this.props = {
      ...props,
    } as Required<AppBuilderProps>;
  }

  /**
   * Build the feature resources (construct composition).
   */
  public build(): this {
    const constructProps = {} as AppConstructProps; // TODO map/normalize from this.props

    new AppConstruct(this.scope, `${this.idPrefix}-AppConstruct`, constructProps);

    return this;
  }

  /**
   * Optional: define CDK outputs in one place.
   */
  public outputs(): this {
    // TODO: add outputs
    return this;
  }
}