// GENERATED BY cdk_ops.sh feature:base-infrastructure
import { Construct } from 'constructs';
import { BaseInfrastructureBuilderProps } from '../interfaces/base-infrastructure';

/**
 * BaseInfrastructureBuilder
 *
 * Purpose:
 *   Composition layer that orchestrates one or more constructs into a cohesive
 *   feature (e.g., Cognito, VPC, ECS, CI/CD).
 *
 * Notes:
 *   - Apply defaults + normalize props here.
 *   - Keep public methods fluent (return this) to support chaining.
 */
export class BaseInfrastructureBuilder {
  private readonly scope: Construct;
  private readonly idPrefix: string;
  private readonly props: Required<BaseInfrastructureBuilderProps>;

  /**
   * BaseInfrastructureBuilder constructor creates a builder that orchestrates
   * one or more constructs into a cohesive feature.
   * @param scope - The construct scope
   * @param idPrefix - The ID prefix for the resources
   * @param props - The builder properties
   */
  constructor(scope: Construct, idPrefix: string, props: BaseInfrastructureBuilderProps) {
    this.scope = scope;
    this.idPrefix = idPrefix;

    // Apply defaults + normalize here
    this.props = {
      ...props,
    } as Required<BaseInfrastructureBuilderProps>;
  }
  
  /**
   * Optional: define CDK outputs in one place.
   */
  public outputs(): this {
    // TODO: add outputs
    return this;
  }
}