// GENERATED BY cdk_ops.sh feature:shared-services1
import { Construct } from 'constructs';
import {
  SharedServices1BuilderProps,
  SharedServices1ConstructProps,
} from '../interfaces/shared-services';
import { SharedServices1Construct } from '../constructs/shared-services-construct';

/**
 * SharedServices1Builder
 *
 * Purpose:
 *   Composition layer that orchestrates one or more constructs into a cohesive
 *   feature (e.g., Cognito, VPC, ECS, CI/CD).
 *
 * Notes:
 *   - Apply defaults + normalize props here.
 *   - Keep public methods fluent (return this) to support chaining.
 */
export class SharedServices1Builder {
  private readonly scope: Construct;
  private readonly idPrefix: string;
  private readonly props: Required<SharedServices1BuilderProps>;

  constructor(
    scope: Construct,
    idPrefix: string,
    props: SharedServices1BuilderProps,
  ) {
    this.scope = scope;
    this.idPrefix = idPrefix;

    // Apply defaults + normalize here
    this.props = {
      ...props,
    } as Required<SharedServices1BuilderProps>;
  }

  /**
   * Build the feature resources (construct composition).
   */
  public build(): this {
    const constructProps = {} as SharedServices1ConstructProps; // TODO map/normalize from this.props

    new SharedServices1Construct(
      this.scope,
      `${this.idPrefix}-SharedServices1Construct`,
      constructProps,
    );

    return this;
  }

  /**
   * Optional: define CDK outputs in one place.
   */
  public outputs(): this {
    // TODO: add outputs
    return this;
  }
}
