// GENERATED BY cdk_ops.sh feature:shared-services
import { Construct } from 'constructs';
import {
  SharedServicesBuilderProps,
  SharedServicesConstructProps,
} from '../interfaces/shared-services';
import { SharedServicesConstruct } from '../constructs/shared-services';

/**
 * SharedServicesBuilder
 *
 * Purpose:
 *   Composition layer that orchestrates one or more constructs into a cohesive
 *   feature (e.g., Cognito, VPC, ECS, CI/CD).
 *
 * Notes:
 *   - Apply defaults + normalize props here.
 *   - Keep public methods fluent (return this) to support chaining.
 */
export class SharedServicesBuilder {
  private readonly scope: Construct;
  private readonly idPrefix: string;
  private readonly props: Required<SharedServicesBuilderProps>;

  /**
   * SharedServicesBuilder constructor creates a builder that orchestrates
   * one or more constructs into a cohesive feature.
   * @param scope - The construct scope
   * @param idPrefix - The ID prefix for the resources
   * @param props - The builder properties
   */
  constructor(
    scope: Construct,
    idPrefix: string,
    props: SharedServicesBuilderProps,
  ) {
    this.scope = scope;
    this.idPrefix = idPrefix;

    // Apply defaults + normalize here
    this.props = {
      ...props,
    } as Required<SharedServicesBuilderProps>;
  }

  /**
   * Build the feature resources (construct composition).
   */
  public build(): this {
    const constructProps = {} as SharedServicesConstructProps; // TODO map/normalize from this.props

    new SharedServicesConstruct(
      this.scope,
      `${this.idPrefix}-SharedServicesConstruct`,
      constructProps,
    );

    return this;
  }

  /**
   * Optional: define CDK outputs in one place.
   */
  public outputs(): this {
    // TODO: add outputs
    return this;
  }
}
